version: "2"
linters:
  exclusions:
    paths:
      - "internal/blst/*"  # disable checking copied files from blst
    rules:
      - linters:
          - staticcheck
        text: "QF1008"   # disable forcing to use the embedded field and omitting the embedded struct
      - linters:
          - govet
        text: "unsafeptr"  # disable flagging unsafeptr usage
formatters:
  exclusions:
    paths:
      - "internal/blst/*"  # disable checking copied files from blst



